# -*- coding: utf-8 -*-
"""NuMeth_Simp_Newtonipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m_jHu6GoL8nGoAJCPE1X_Uzm5VjJQ9Dt
"""

import numpy as np
import matplotlib.pyplot as plt

"""### Simple Iteration ( Brute Force) 

"""

#For single root.
def b_force(f,h):
  epochs = 100
  x_roots = []
  for epoch in range(epochs):
    x_guess = f(h)
    print(x_guess)
    if x_guess == 0:
      x_roots.append(h)
      break
    else:
         h+=1
  return print(f"The root is: {x_roots}, found at epoch {epoch}")

# Finding n number of roots.
def brute_nforce(f,h):
  epochs = 100
  n_roots = 3
  x_roots = []
  end_epoch = 0
  for epoch in range(epochs):
    print(f(h))
    if np.allclose(0,f(h)):
      x_roots.append(h)
      end_epoch = epoch
      if len(x_roots)==n_roots:
        break
    h+=1
  return print(f"The roots are: {x_roots}, found at epoch {end_epoch+1}")

"""### Newton Method"""

## Single Root
def newt_R(f,f_prime):
  epochs = 100
  x = 0
  root = 0
  for epoch in range(epochs):
    x_prime = x - (f(x)/f_prime(x))
    if np.allclose(x, x_prime):
      root = x
      break
    x = x_prime
  return print(f"The root is: {root}, found at epoch {epoch}")

# Findng n number of  roots 
def newt_N(f,f_prime):
  epochs = 100
  x_inits = np.arange(0,5)
  roots = []
  for x_init in x_inits:
    print("Iteration Number: ", x_init)
    x = x_init
    print("x is: ", x)
    for epoch in range(epochs):
      print("Epoch: ", epoch)
      x_prime = x - (f(x)/f_prime(x))
      print("x prime is: ", x_prime)
      if np.allclose(x, x_prime):
        roots.append(x)
        print("roots: ", roots)
        break
      x = x_prime
      print("x final: ", x)
    
  print("np_roots before round: ",roots)
  np_roots = np.round(roots,3)
  print("np_roots after round: ", np_roots)
  np_roots = np.unique(np_roots)
  print("np_roots after sorting to unique: ", np_roots)
  return np_roots